apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-prod-vcluster
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    clusterName: env-prod
spec:
  project: default
  sources:
    - path: platform-infra/clusters/prod/ingress
      repoURL: https://github.com/ekalabs/crossplane-vcluster.git
      targetRevision: feat/argo-crossplane-preview-qa-stage-prod-migration
    
    - repoURL: https://charts.loft.sh
      targetRevision: 0.22.0
      chart: vcluster
      helm:
        releaseName: env-prod
        values: |
          pro: false
          exportKubeConfig:
            context: env-prod
            server: https://env-prod.appfactory.local:32443
            secret:
              name: vc-env-prod-ext
              namespace: env-prod
          sync:
            toHost:
              ingresses:
                enabled: true
          controlPlane:
            distro:
              k3s:
                enabled: true
            proxy:
              extraSANs:
              - env-prod
              - env-prod.env-prod
              - env-prod.env-prod.svc
              - env-prod.env-prod.svc.cluster.local
            statefulSet:
              scheduling:
                podManagementPolicy: OrderedReady
                    
  destination:
    server: https://kubernetes.default.svc
    namespace: env-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true