apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-kyverno-prereq
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.7.1
    helm:
      values: |
        admissionController:
          replicas: 1
          apiPriorityAndFairness: true
          startupProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 6
          readinessProbe:
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          container:
            resources:
              limits:
                memory: 768Mi
              requests:
                cpu: 200m
                memory: 256Mi
        backgroundController:
          enabled: false
          replicas: 1
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        cleanupController:
          enabled: false
        reportsController:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m
