---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: openbao
spec:
  forProvider:
    chart:
      name: openbao
      repository: https://openbao.github.io/openbao-helm
      version: 0.8.0
    namespace: openbao
    values:
      server:
        dev:
          enabled: true
          devRootToken: root
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - host: openbao.env-management.appfactory.local
              paths:
                - /
  providerConfigRef:
    name: provider-helm
