---
apiVersion: v1
kind: Secret
metadata:
  name: my-repo
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ekalabs/crossplane-vcluster-env.git