apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../environments/applicationsets/env-management-components.yaml
  - ../../../environments/applicationsets/env-green-apps.yaml
  - ../../../environments/applicationsets/env-yellow-apps.yaml
