apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd/appsets/env-management-components.yaml
  - argocd/appsets/env-green-apps.yaml
  - argocd/appsets/env-yellow-apps.yaml
