---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-delivery
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - path: platform-delivery
      repoURL: https://github.com/ekalabs/crossplane-vcluster.git
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

