apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusters/namespaces/env-management.yaml
  - clusters/namespaces/env-preview.yaml
  - clusters/namespaces/env-qa.yaml
  - clusters/namespaces/env-stage.yaml
  - clusters/namespaces/env-prodlike.yaml
  - clusters/namespaces/env-prod.yaml
  - clusters/management/vcluster.yaml
  - clusters/management/bootstrap.yaml
  - clusters/management/crossplane-providers.yaml
  - clusters/preview/vcluster.yaml
  - clusters/preview/bootstrap.yaml
  - clusters/preview/crossplane-providers.yaml
  - clusters/qa/vcluster.yaml
  - clusters/qa/bootstrap.yaml
  - clusters/qa/crossplane-providers.yaml
  - clusters/stage/vcluster.yaml
  - clusters/stage/bootstrap.yaml
  - clusters/stage/crossplane-providers.yaml
  - clusters/prodlike/vcluster.yaml
  - clusters/prodlike/bootstrap.yaml
  - clusters/prodlike/crossplane-providers.yaml
  - clusters/prod/vcluster.yaml
  - clusters/prod/bootstrap.yaml
  - clusters/prod/crossplane-providers.yaml
