---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-helm
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: env-management
      name: vc-env-management-ext
      key: config

---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: keycloak
spec:
  forProvider:
    chart:
      name: keycloak
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 24.9.0
    namespace: keycloak
    values:
      global:
        security:
          allowInsecureImages: true
      image:
        registry: docker.io
        repository: bitnamilegacy/keycloak
        tag: 26.3.2-debian-12-r0
        pullPolicy: IfNotPresent
      postgresql:
        image:
          registry: docker.io
          repository: bitnamilegacy/postgresql
          tag: 17.4.0-debian-12-r17
          pullPolicy: IfNotPresent
      auth:
        adminUser: admin
        adminPassword: change-me
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
          namespace: monitoring
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: /metrics
      extraEnvVars:
        - name: KEYCLOAK_HOSTNAME
          value: http://keycloak.env-management.appfactory.local:32080/
      ingress:
        enabled: true
        ingressClassName: traefik
        hostname: keycloak.env-management.appfactory.local
  providerConfigRef:
    name: provider-helm
